### ISSUE TITLE
Could not connect to Uponor controller on IP address

### ISSUE THREAD

**Issue by vmbaggum** [ChrisTerBeke/homey-uponor#11]
Hi,

Some of our T-169 thermostats are working some of them aren't working and throw the following error: 
"Device Unavailable Could not connect to Uponor controller on IP address x.x.x.x".

Even after a restart of the app not all of them are working

**Comment by ChrisTerBeke** [comment]
Hi,

Could it be possible that the communication module has changed IP addresses in your network?

Chris

**Comment by vmbaggum** [comment]
Hi,

No the IP address of the controller did not change. If I check the thermostat device in Homey that is in an error state, the last API call does show the full JSON with a "result":"OK" and full output. On the Homey community there are 2 others with the same issue. Is it possible that with multiple Thermostats (I have 8) the issue occurs? Maybe a timeout or to many API calls?

**Comment by vmbaggum** [comment]
After adding (with the same IP as the IP of the controller hasn't changed) or removing the override IP Address the thermostat comes back online. Looks like it is throwing the error on line 39 of the device.ts when it shouldn't.

**Comment by ChrisTerBeke** [comment]
Thanks for that additional information, I'll have a look at the behavior of the IP override setting.

**Comment by nf-dk** [comment]
I have the same problem. But it seems it helps if I remove or add the IP adresse on the device. Then it works for a while. then it stops working, and I can do the reverse thing and it works again.

**Comment by vmbaggum** [comment]
Hi, I see there was an update "Versie 0.0.8 — Fixed IP address settings" but I still have the same issue that some of the thermostats are throwing an error. The number and order of thermostats in error changes per restart. I have 8 thermostats in total.

**Comment by ChrisTerBeke** [comment]
Hi @vmbaggum,

The issue will be addressed in the next release, which I'm now testing internally. Should be out in a few days.

**Comment by ChrisTerBeke** [comment]
I have released a test version which you can install here: https://homey.app/nl-nl/app/com.christerbeke.uponor-smatrix/Uponor-Smatrix/test/.

**Comment by vmbaggum** [comment]
When I open the link:

https://homey.app/nl-nl/app/com.christerbeke.uponor-smatrix/Uponor-Smatrix/test/

I'm getting redirected to:

https://homey.app/nl-nl/app/com.christerbeke.uponor-smatrix/Uponor-Smatrix/

There the latest version is v0.9 from yesterday and that is the version I'm running right now and experiencing the same issue.

**Comment by ChrisTerBeke** [comment]
I have release v0.0.10 with additional bug fixes. Can you test again?

**Comment by vmbaggum** [comment]
Unfortunately still the same issue: "Device Unavailable Could not connect to Uponor controller on local network"
After some time it comes back online but another one goes offline, it is possible the API of the Uponor cannot handle the requests?

**Comment by irekvist** [comment]
I have the exact same issue, some shows up but most of them are not accessible.

**Comment by vmbaggum** [comment]
Looks like increasing the timeout in v0.11 solved the issue! All thermostats (8) are working now! Thanks for the update!

**Comment by vmbaggum** [comment]
Spoke to soon, now I'm getting the error "app unavailable" in the device overview and "Memory Warning Limit Reached" in the App overview.

**Comment by ChrisTerBeke** [comment]
Currently the architecture of the app creates an API call for every added Homey device. For larger number of thermostats this might lead to issues with memory, either in Homey or on the Uponor control unit. I have started a rewrite to follow the architecture of my other app (Remeha Home) to only do a single API call for all devices (from the "driver" part of the Homey app) and have the devices pull the data from the driver. This should reduce network calls for every use, increase network performance for larger installations and hopefully mitigate the memory issues. It might take a few weeks to complete and test this rewrite.

**Comment by smeijer1990** [comment]
Hi,

Im not getting any of mine uponor r-208 to link to homey. The app keeps saying there aren't any found and that i should try to type in my ip adres, but it also says that automatically pairing is the best setting. I have no clue to where i can find these settings. I am new to homey so this is the first time i am setting uponor up in the homey, worked fine with Google home.

I have tried 
Restart homey 
Searched up my ip adres on my desktop and the ip adres of my phone (wired en Wireless) tried filling in these ip adresses but nothing came up.
Put the uponor system back to Wireless en tried again 
 
Hope someone can help

**Comment by vmbaggum** [comment]
Since the 0.1.0 update nothing can be read anymore from the R-208, none of the thermostats are reporting anymore.

**Comment by ChrisTerBeke** [comment]
I am still not able to reproduce any of these reports, so unfortunately I'm out of options. Please investigate your network setup to ensure that Homey is able to reach the IP address of the Uponor control unit.
